name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # This cron syntax schedules the job to run every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest  # The environment where the script will run
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Specify the version of Python you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Python Script
        env:
            URL_SC_TOKEN: ${{ secrets.URL_SC_TOKEN }}
            URL_HS_TOKEN: ${{ secrets.URL_HS_TOKEN}}
            SC_USER: ${{ secrets.SC_USER }}
            PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python res_sarnia/src/main.py  # Replace with the path to your script
